add_test_subctl_benchmark
manosnoam/ocp-multi-cluster-tester pull request #37
Opened 2021-02-23 11:29 UTC by pinikomarov

This CI Test will test if subctl benchmarks are working fine

2021-03-01 08:39 UTC, manosnoam requested changes

2021-03-01 08:39 UTC, manosnoam commented on setup_subm.sh
> +  export "KUBECONFIG=${KUBECONF_CLUSTER_B}"
If we need both clusters accessible, please change it to: 
`export KUBECONFIG="${KUBECONF_CLUSTER_A}:${KUBECONF_CLUSTER_B}"`

2021-03-01 08:39 UTC, manosnoam commented on setup_subm.sh
> +  subctl benchmark throughput ${KUBECONF_CLUSTER_A} ${KUBECONF_CLUSTER_B}
When referring here to "${KUBECONF_CLUSTER_A}" and  "${KUBECONF_CLUSTER_B}"
did you mean the cluster name/id ? 

e.g.
`subctl benchmark latency ${CLUSTER_A_NAME} ${CLUSTER_B_NAME}`

if it's the kubeconfig file (and not cluster name/id), then the previous command of exporting kubeconfig seems to be redundant.

2021-03-01 09:58 UTC, pinikomarov reviewed
removed the "export" lines

2021-03-01 09:58 UTC, pinikomarov commented on setup_subm.sh
> +  subctl benchmark throughput ${KUBECONF_CLUSTER_A} ${KUBECONF_CLUSTER_B}
correct , the previous export statements are redundant, I'll change that..

2021-03-02 14:01 UTC, manosnoam requested changes
You did not call the test, but only defined it.
Can you call it on line 4164 
https://github.com/manosnoam/ocp-multi-cluster-tester/blob/cb0fdcfb6a6a1f2c68c368f4b30404ef360e54a4/setup_subm.sh#L4164

`${junit_cmd} test_subctl_benchmarks`

2021-03-22 08:48 UTC, closed without merging