add_test_subctl_benchmark
manosnoam/ocp-multi-cluster-tester pull request #43
Opened 2021-03-22 08:44 UTC by pinikomarov

2021-03-24 08:42 UTC, manosnoam requested changes

2021-03-24 08:42 UTC, manosnoam commented on setup_subm.sh
> +        fi
1) `test_subctl_benchmarks` function does not output to $E2E_LOG file, so there's no point in tailing that file after benchmark.

2) Tailing the benchmark output for "failure" is only useful if the exit status is always 0 (even if there are benchmark failures). For example, in `subctl verify` that's the case, so in order to know if e2e failed, I'm grepping for 'FAIL!'.
Does benchmark show a failure message we can grep upon ?

3) If it does, we can grep for those failure messages, or alternatively - verify successful output (for example, with the `highlight` function).

4) If it does not, and if benchmark returns non-zero exit code when it fails, then do: 
`${junit_cmd} test_subctl_benchmarks || subctl_benchmarks_status=FAILED

2021-04-13 12:26 UTC, pinikomarov commented
going to check if ||false will work here ...

[r@r20 submariner-operator]$ ./bin/subctl benchmark latency output/kubeconfigs/kind-config-cluster1 output/kubeconfigs/kind-config-cluster2

2021-04-25 22:22 UTC, pinikomarov commented
comments applied here : https://github.com/manosnoam/ocp-multi-cluster-tester/pull/44

2021-04-25 22:22 UTC, closed without merging